export const AUTH_PATH = "/auth"
export const ANIMALS_PATH = "/animals"
export const ADOPTIONS_PATH="/adoptions"
export const DOCUMENTS_PATH="/document"
export const FIREBASE_USERS_PATH="/users-firebase"
export const REPORT_PATH="/report"